// BACKEND INTEGRATION POINT: Replace all mock data with API calls to your PHP Yii2 backend.

// Notification types matching the base project's DashboardHeader notification types
export type NotificationType = "update" | "alert" | "info";

export type TargetAudience = "all" | "individual" | "industry" | "company" | "access" | "dataset";

export interface AdminNotification {
  id: string;
  title: string;
  message: string;
  type: NotificationType;
  targetAudience: TargetAudience;
  targetDetails: string; // e.g., specific email, industry name, company name, category
  recipientCount: number;
  sentDate: string;
  sentTime: string;
  sentBy: string;
}

// BACKEND INTEGRATION POINT: GET /api/admin/notifications?limit=20
export const mockNotifications: AdminNotification[] = [
  {
    id: "n1",
    title: "New Dataset Available",
    message: "Carbon Fiber Market Q4 2024 data has been updated with the latest industry figures.",
    type: "update",
    targetAudience: "industry",
    targetDetails: "Composites",
    recipientCount: 342,
    sentDate: "2026-04-01",
    sentTime: "14:30:00",
    sentBy: "Admin",
  },
  {
    id: "n2",
    title: "Subscription Expiring Reminder",
    message: "Your subscription is expiring soon. Please renew to maintain uninterrupted access.",
    type: "alert",
    targetAudience: "all",
    targetDetails: "All Users",
    recipientCount: 1247,
    sentDate: "2026-03-31",
    sentTime: "09:00:00",
    sentBy: "Admin",
  },
  {
    id: "n3",
    title: "New Dashboard Added",
    message: "EV Battery Market dashboard now includes regional forecasts and trend analysis.",
    type: "info",
    targetAudience: "industry",
    targetDetails: "Automotive & Transportation",
    recipientCount: 189,
    sentDate: "2026-03-30",
    sentTime: "16:15:00",
    sentBy: "Admin",
  },
  {
    id: "n4",
    title: "System Maintenance Notice",
    message: "Scheduled maintenance on April 5th from 2 AM to 4 AM UTC. Services may be briefly unavailable.",
    type: "alert",
    targetAudience: "all",
    targetDetails: "All Users",
    recipientCount: 1247,
    sentDate: "2026-03-29",
    sentTime: "10:00:00",
    sentBy: "Admin",
  },
  {
    id: "n5",
    title: "Exclusive Report Available",
    message: "A new exclusive report on defense spending trends is now available in your dashboard.",
    type: "update",
    targetAudience: "access",
    targetDetails: "Aerospace & Defense datasets",
    recipientCount: 56,
    sentDate: "2026-03-28",
    sentTime: "11:30:00",
    sentBy: "Admin",
  },
  {
    id: "n6",
    title: "Welcome to Stratview One",
    message: "Thank you for joining! Explore our dashboards and datasets to get started.",
    type: "info",
    targetAudience: "individual",
    targetDetails: "sarah.chen@techcorp.com",
    recipientCount: 1,
    sentDate: "2026-03-27",
    sentTime: "14:23:00",
    sentBy: "Admin",
  },
  {
    id: "n7",
    title: "Data Update: Glass Fiber Composites",
    message: "Glass Fiber Composites dataset has been refreshed with March 2026 data.",
    type: "update",
    targetAudience: "company",
    targetDetails: "TechCorp Inc.",
    recipientCount: 3,
    sentDate: "2026-03-26",
    sentTime: "08:45:00",
    sentBy: "Admin",
  },
  {
    id: "n8",
    title: "Feature Update: Enhanced Filters",
    message: "We've added new filtering options to all dashboards for better data exploration.",
    type: "info",
    targetAudience: "all",
    targetDetails: "All Users",
    recipientCount: 1247,
    sentDate: "2026-03-25",
    sentTime: "13:00:00",
    sentBy: "Admin",
  },
  {
    id: "n9",
    title: "Urgent: Data Correction",
    message: "A correction has been made to the Aircraft Interiors Q3 dataset. Please review your reports.",
    type: "alert",
    targetAudience: "access",
    targetDetails: "Aircraft Interiors dataset",
    recipientCount: 24,
    sentDate: "2026-03-24",
    sentTime: "17:00:00",
    sentBy: "Admin",
  },
  {
    id: "n10",
    title: "New Industry Coverage",
    message: "We've expanded our coverage to include Mining, Metals & Minerals industry datasets.",
    type: "update",
    targetAudience: "industry",
    targetDetails: "Mining, Metals & Minerals",
    recipientCount: 87,
    sentDate: "2026-03-23",
    sentTime: "10:30:00",
    sentBy: "Admin",
  },
  {
    id: "n11",
    title: "Password Policy Update",
    message: "We've updated our password policy. All users must reset their passwords within the next 30 days to comply with the new security requirements.",
    type: "alert",
    targetAudience: "all",
    targetDetails: "All Users",
    recipientCount: 1247,
    sentDate: "2026-03-22",
    sentTime: "08:00:00",
    sentBy: "Admin",
  },
  {
    id: "n12",
    title: "Quarterly Report Available",
    message: "The Q1 2026 composites market quarterly report is now available for download in your dashboard.",
    type: "update",
    targetAudience: "industry",
    targetDetails: "Composites",
    recipientCount: 342,
    sentDate: "2026-03-21",
    sentTime: "15:00:00",
    sentBy: "Admin",
  },
  {
    id: "n13",
    title: "Webinar Invitation",
    message: "Join our upcoming webinar on 'Future of EV Battery Materials' on April 10th at 3 PM UTC. Register from your dashboard.",
    type: "info",
    targetAudience: "industry",
    targetDetails: "Automotive & Transportation",
    recipientCount: 189,
    sentDate: "2026-03-20",
    sentTime: "11:00:00",
    sentBy: "Admin",
  },
  {
    id: "n14",
    title: "Access Granted: Defense Systems",
    message: "You have been granted access to the Defense Systems dataset. Explore the latest data and insights now.",
    type: "info",
    targetAudience: "individual",
    targetDetails: "j.martinez@globalind.com",
    recipientCount: 1,
    sentDate: "2026-03-19",
    sentTime: "14:20:00",
    sentBy: "Admin",
  },
  {
    id: "n15",
    title: "Data Refresh: Polymer Matrix Composites",
    message: "The Polymer Matrix Composites dataset has been refreshed with the latest February 2026 data points and revised forecasts.",
    type: "update",
    targetAudience: "access",
    targetDetails: "Composites datasets",
    recipientCount: 156,
    sentDate: "2026-03-18",
    sentTime: "09:30:00",
    sentBy: "Admin",
  },
  {
    id: "n16",
    title: "New Feature: Export to Excel",
    message: "You can now export dashboard data directly to Excel format. Look for the new export button on each dashboard.",
    type: "info",
    targetAudience: "all",
    targetDetails: "All Users",
    recipientCount: 1247,
    sentDate: "2026-03-17",
    sentTime: "12:00:00",
    sentBy: "Admin",
  },
  {
    id: "n17",
    title: "Subscription Renewed",
    message: "Your company subscription has been renewed successfully for another 12 months. Thank you for your continued partnership.",
    type: "info",
    targetAudience: "company",
    targetDetails: "Acme Corp",
    recipientCount: 5,
    sentDate: "2026-03-16",
    sentTime: "10:45:00",
    sentBy: "Admin",
  },
  {
    id: "n18",
    title: "Dashboard Redesign: Aerospace",
    message: "The Aerospace & Defense dashboard has been redesigned with improved visualizations and new filtering capabilities.",
    type: "update",
    targetAudience: "access",
    targetDetails: "Aerospace & Defense datasets",
    recipientCount: 56,
    sentDate: "2026-03-15",
    sentTime: "16:30:00",
    sentBy: "Admin",
  },
  {
    id: "n19",
    title: "Upcoming Price Revision",
    message: "Please note that subscription prices will be revised from May 1st, 2026. Current subscribers will be grandfathered at existing rates.",
    type: "alert",
    targetAudience: "all",
    targetDetails: "All Users",
    recipientCount: 1247,
    sentDate: "2026-03-14",
    sentTime: "09:00:00",
    sentBy: "Admin",
  },
  {
    id: "n20",
    title: "New Dataset: Smart Materials",
    message: "Introducing our new Smart Materials & Metamaterials dataset covering market size, trends, and forecasts through 2032.",
    type: "update",
    targetAudience: "industry",
    targetDetails: "Chemical & Materials",
    recipientCount: 203,
    sentDate: "2026-03-13",
    sentTime: "13:15:00",
    sentBy: "Admin",
  },
];

// Industries list for targeting
export const industryOptions = [
  "Aerospace & Defense",
  "Automotive & Transportation",
  "Building & Construction",
  "Chemical & Materials",
  "Composites",
  "Consumer Goods & Services",
  "Disruptive Technology",
  "Electrical & Electronics",
  "Energy & Power",
  "Engineering",
  "Healthcare",
  "Information & Communications Technology",
  "Mining, Metals & Minerals",
  "Packaging",
];

// Unique companies from users mock
export const companyOptions = [
  "TechCorp Inc.",
  "Global Industries",
  "InnovaLabs",
  "Acme Corp",
  "FutureTech",
  "NexGen Solutions",
  "BlueWave Analytics",
  "DataDriven",
  "SmartSys",
  "Peak Industries",
  "Quantum Research",
  "LatAm Tech",
];

// Category options for access-based targeting
export const categoryOptions = [
  "Composites",
  "Aerospace & Defense",
  "Automotive & Transportation",
];

// Dataset options for dataset-based targeting
export const datasetOptions = [
  "Carbon Fiber Market",
  "Glass Fiber Composites",
  "Polymer Matrix Composites",
  "Aircraft Interiors",
  "Commercial Aircraft",
  "Defense Systems",
  "Electric Vehicle Market",
];
